import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

// ✅ Переименовали: roboto вместо Roboto
const roboto = Roboto({
  weight: ["400", "500", "700"], // ✅ Рекомендуется указать вес
  subsets: ["latin"],
  variable: "--font-roboto",     // ✅ Лучше писать в kebab-case: roboto, а не ROBOTO
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: "/logo.svg",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}